# Generated by Django 5.2.5 on 2026-08-28 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("universities", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faculty",
            options={"ordering": ("name",), "verbose_name_plural": "Faculties"},
        ),
        migrations.AlterModelOptions(
            name="specialty",
            options={"ordering": ("name",), "verbose_name_plural": "Specialties"},
        ),
    ]
