version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-alumni_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-alumni_password_2026}
      - POSTGRES_DB=${POSTGRES_DB:-alumni_db}
    networks:
      - alumni_network

  backend:
    build: ./backend
    restart: always
    command: gunicorn --bind 0.0.0.0:8000 config.wsgi:application
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - USE_POSTGRES=true
      - POSTGRES_DB=${POSTGRES_DB:-alumni_db}
      - POSTGRES_USER=${POSTGRES_USER:-alumni_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-alumni_password_2026}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-django-insecure-secret-key-qardu-alumni-production-2026}
      - DJANGO_DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_ADMIN_CHAT_ID=${TELEGRAM_ADMIN_CHAT_ID}
      - CSRF_TRUSTED_ORIGINS=http://${DOMAIN:-89.39.95.153},https://${DOMAIN:-89.39.95.153},http://89.39.95.153,http://localhost:3000
      - CORS_ALLOWED_ORIGINS=http://${DOMAIN:-89.39.95.153},https://${DOMAIN:-89.39.95.153},http://89.39.95.153,http://localhost:3000
    ports:
      - "127.0.0.1:8005:8000"
    depends_on:
      - db
    networks:
      - alumni_network

  frontend:
    build: ./frontend
    restart: always
    environment:
      - API_URL=http://backend:8000/api/v1
      - NEXT_PUBLIC_API_URL=http://${DOMAIN:-89.39.95.153}/api/v1
    ports:
      - "127.0.0.1:3005:3000"
    networks:
      - alumni_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  alumni_network:
