# Generated by Django 5.2.5 on 2026-09-15 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0008_educationexperience"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=64, unique=True)),
                ("name_uz", models.CharField(max_length=180)),
                ("name_en", models.CharField(blank=True, max_length=180)),
                ("name_ru", models.CharField(blank=True, max_length=180)),
                ("description_uz", models.TextField(max_length=500)),
                ("description_en", models.TextField(blank=True, max_length=500)),
                ("description_ru", models.TextField(blank=True, max_length=500)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "career",
                                "Career Impact (Ishga joylashtirish va amaliyot)",
                            ),
                            ("mentorship", "Mentorship Impact (Ustoz-shogirdlik)"),
                            (
                                "university",
                                "University Contribution (Universitetga ko‘mak)",
                            ),
                            (
                                "community",
                                "Community Contribution (Hamjamiyat va tadbirlar)",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "threshold",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Talab qilinadigan tasdiqlangan hissa yoki ball miqdori",
                    ),
                ),
                ("icon_key", models.CharField(default="award", max_length=64)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "E’tirof nishoni",
                "verbose_name_plural": "E’tirof nishonlari",
                "ordering": ("category", "threshold", "id"),
            },
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "career",
                                "Career Impact (Ishga joylashtirish va amaliyot)",
                            ),
                            ("mentorship", "Mentorship Impact (Ustoz-shogirdlik)"),
                            (
                                "university",
                                "University Contribution (Universitetga ko‘mak)",
                            ),
                            (
                                "community",
                                "Community Contribution (Hamjamiyat va tadbirlar)",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("alumni_hired", "Bitiruvchini ishga qabul qilish"),
                            (
                                "student_internship",
                                "Talabaga amaliyot (internship) taqdim etish",
                            ),
                            (
                                "job_placement_confirmed",
                                "Ish bilan ta’minlashda ko‘maklashish",
                            ),
                            ("mentorship_completed", "Mentorlik dasturini yakunlash"),
                            (
                                "mentee_outcome_verified",
                                "Shogirdning kasbiy natijasini tasdiqlash",
                            ),
                            (
                                "university_project_support",
                                "Universitet loyihasini qo‘llab-quvvatlash",
                            ),
                            ("financial_support", "Moddiy / grant ko‘magi"),
                            (
                                "equipment_support",
                                "Laboratoriya yoki texnik vosita taqdim etish",
                            ),
                            (
                                "scholarship_support",
                                "Talabalarga maxsus stipendiya ajratish",
                            ),
                            ("event_organized", "Alumni tadbiri tashkilotchisi"),
                            ("event_speaker", "Tadbir yoki anjumanda spikerlik"),
                            (
                                "masterclass_delivered",
                                "Mahorat darsi yoki seminar o‘tkazish",
                            ),
                            ("community_initiative", "Hamjamiyat rivoji tashabbusi"),
                        ],
                        db_index=True,
                        max_length=48,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("self_reported", "Foydalanuvchi arizasi"),
                            ("system_generated", "Tizim orqali yaratilgan"),
                            ("event", "Universitet tadbiri"),
                            ("staff_entry", "Universitet xodimi kiritgan"),
                        ],
                        default="self_reported",
                        max_length=32,
                    ),
                ),
                ("source_id", models.CharField(blank=True, max_length=120)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, max_length=2000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("verified", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                            ("revoked", "Bekor qilingan"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("rejection_reason", models.TextField(blank=True, max_length=1000)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_contributions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tasdiqlangan hissa",
                "verbose_name_plural": "Bitiruvchilar hissalari",
                "ordering": ("-occurred_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="ScoreTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            (
                                "career",
                                "Career Impact (Ishga joylashtirish va amaliyot)",
                            ),
                            ("mentorship", "Mentorship Impact (Ustoz-shogirdlik)"),
                            (
                                "university",
                                "University Contribution (Universitetga ko‘mak)",
                            ),
                            (
                                "community",
                                "Community Contribution (Hamjamiyat va tadbirlar)",
                            ),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "points",
                    models.IntegerField(
                        help_text="Qo‘shiladigan (musbat) yoki qaytariladigan (manfiy) ball"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("award", "Hissa balli qo‘shildi"),
                            ("reversal", "Hissa balli bekor qilindi"),
                            ("correction", "Tahrirlash / Korreksiya"),
                        ],
                        db_index=True,
                        default="award",
                        max_length=24,
                    ),
                ),
                (
                    "scoring_rule_version",
                    models.CharField(default="v1.0", max_length=32),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_transactions",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "contribution",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_transactions",
                        to="impact.contribution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hissa balli tranzaksiyasi",
                "verbose_name_plural": "Hissa ballari ledgeri",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="AlumniAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "achievement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awardees",
                        to="impact.achievement",
                    ),
                ),
                (
                    "alumni",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements_earned",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitiruvchi erishgan nishon",
                "verbose_name_plural": "Bitiruvchilarning nishonlari",
                "ordering": ("-awarded_at",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("alumni", "achievement"),
                        name="unique_alumni_achievement",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["alumni", "category", "status"],
                name="contrib_alumni_cat_st_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["status", "occurred_at"], name="contrib_st_occurred_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="contribution",
            index=models.Index(
                fields=["category", "action_type"], name="contrib_cat_action_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scoretransaction",
            index=models.Index(
                fields=["alumni", "category", "created_at"],
                name="score_tx_alumni_cat_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scoretransaction",
            index=models.Index(
                fields=["transaction_type", "created_at"],
                name="score_tx_type_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scoretransaction",
            index=models.Index(
                fields=["contribution", "transaction_type"],
                name="score_tx_contrib_type_idx",
            ),
        ),
    ]
