# Generated by Django 5.2.5 on 2026-08-26 13:45

import apps.alumni.models
import apps.editorial.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0002_achievement_alumnisource_careertimelineitem_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("title_uz", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                ("summary_uz", models.CharField(max_length=420)),
                ("summary_en", models.CharField(blank=True, max_length=420)),
                ("description_uz", models.TextField(max_length=7000)),
                ("description_en", models.TextField(blank=True, max_length=7000)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("meetup", "Alumni Meetup"),
                            ("reunion", "Reunion"),
                            ("conference", "University Conference"),
                            ("guest_lecture", "Guest Lecture"),
                            ("anniversary", "Anniversary"),
                            ("award", "Award Ceremony"),
                            ("career_talk", "Career Talk"),
                            ("public_lecture", "Public Lecture"),
                            ("networking", "Networking Event"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.editorial.models.editorial_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.alumni.models.validate_avatar_size,
                        ],
                    ),
                ),
                ("start_at", models.DateTimeField(db_index=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("offline", "Offline"),
                            ("online", "Online"),
                            ("hybrid", "Hybrid"),
                        ],
                        max_length=12,
                    ),
                ),
                ("location_uz", models.CharField(max_length=260)),
                ("location_en", models.CharField(blank=True, max_length=260)),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[apps.alumni.models.validate_https_url],
                    ),
                ),
            ],
            options={
                "ordering": ("start_at",),
            },
        ),
        migrations.CreateModel(
            name="AlumniInterview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("title_uz", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                ("intro_uz", models.TextField(max_length=1800)),
                ("intro_en", models.TextField(blank=True, max_length=1800)),
                ("pull_quote_uz", models.CharField(blank=True, max_length=420)),
                ("pull_quote_en", models.CharField(blank=True, max_length=420)),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="interviews",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_featured", "-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="EventSpeaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_name", models.CharField(blank=True, max_length=180)),
                ("role_uz", models.CharField(blank=True, max_length=180)),
                ("role_en", models.CharField(blank=True, max_length=180)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "alumnus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="speaker_links",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_links",
                        to="editorial.event",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="event",
            name="speakers",
            field=models.ManyToManyField(
                blank=True,
                related_name="events",
                through="editorial.EventSpeaker",
                to="alumni.alumniprofile",
            ),
        ),
        migrations.CreateModel(
            name="InterviewItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_uz", models.CharField(max_length=500)),
                ("question_en", models.CharField(blank=True, max_length=500)),
                ("answer_uz", models.TextField(max_length=5000)),
                ("answer_en", models.TextField(blank=True, max_length=5000)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="editorial.alumniinterview",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="AlumniAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("career", "Career"),
                            ("study", "Study"),
                            ("leadership", "Leadership"),
                            ("personal_growth", "Personal growth"),
                            ("industry", "Industry"),
                            ("life", "Life lesson"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title_uz", models.CharField(blank=True, max_length=180)),
                ("title_en", models.CharField(blank=True, max_length=180)),
                ("content_uz", models.TextField(blank=True, max_length=1600)),
                ("content_en", models.TextField(blank=True, max_length=1600)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("manual", "Manual"), ("interview", "Interview")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="advice",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "source_interview_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="derived_advice",
                        to="editorial.interviewitem",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_featured", "-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="SuccessStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("title_uz", models.CharField(max_length=220)),
                ("title_en", models.CharField(blank=True, max_length=220)),
                ("summary_uz", models.CharField(max_length=420)),
                ("summary_en", models.CharField(blank=True, max_length=420)),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.editorial.models.editorial_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.alumni.models.validate_avatar_size,
                        ],
                    ),
                ),
                ("student_takeaway_uz", models.TextField(blank=True, max_length=1600)),
                ("student_takeaway_en", models.TextField(blank=True, max_length=1600)),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="success_stories",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_featured", "-published_at", "-created_at"),
            },
        ),
        migrations.CreateModel(
            name="StorySection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("introduction", "Introduction"),
                            ("university", "University years"),
                            ("early_career", "Early career"),
                            ("turning_point", "Turning point"),
                            ("achievements", "Major achievements"),
                            ("current_impact", "Current impact"),
                            ("reflection", "Advice / reflection"),
                        ],
                        max_length=24,
                    ),
                ),
                ("heading_uz", models.CharField(blank=True, max_length=180)),
                ("heading_en", models.CharField(blank=True, max_length=180)),
                ("content_uz", models.TextField(max_length=6000)),
                ("content_en", models.TextField(blank=True, max_length=6000)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="editorial.successstory",
                    ),
                ),
            ],
            options={
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddIndex(
            model_name="alumniinterview",
            index=models.Index(
                fields=["is_published", "published_at"], name="interview_pub_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventspeaker",
            constraint=models.UniqueConstraint(
                fields=("event", "order"), name="unique_event_speaker_order"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["is_published", "start_at"], name="event_pub_start_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="interviewitem",
            constraint=models.UniqueConstraint(
                fields=("interview", "order"), name="unique_interview_item_order"
            ),
        ),
        migrations.AddIndex(
            model_name="alumniadvice",
            index=models.Index(
                fields=["is_published", "category"], name="advice_pub_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="successstory",
            index=models.Index(
                fields=["is_published", "published_at"], name="story_pub_date_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storysection",
            constraint=models.UniqueConstraint(
                fields=("story", "order"), name="unique_story_section_order"
            ),
        ),
    ]
