# Generated by Django 5.2.5 on 2026-08-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("meetup", "Alumni Meetup"),
                    ("reunion", "Reunion"),
                    ("conference", "University Conference"),
                    ("guest_lecture", "Guest Lecture"),
                    ("anniversary", "Anniversary"),
                    ("award", "Award Ceremony"),
                    ("career_talk", "Career Talk"),
                    ("public_lecture", "Public Lecture"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
