# Generated by Django 5.2.5 on 2026-08-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0003_event_cover_image_alt_event_cover_image_credit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniadvice",
            name="content_ru",
            field=models.TextField(blank=True, max_length=1600),
        ),
        migrations.AddField(
            model_name="alumniadvice",
            name="title_ru",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
