# Generated by Django 5.2.5 on 2026-09-21 20:26

import apps.alumni.models
import apps.editorial.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0004_alumniadvice_content_ru_alumniadvice_title_ru"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_published", models.BooleanField(db_index=True, default=False)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=190, unique=True)),
                ("title_uz", models.CharField(max_length=240)),
                ("title_ru", models.CharField(blank=True, max_length=240)),
                ("title_en", models.CharField(blank=True, max_length=240)),
                ("summary_uz", models.CharField(max_length=450)),
                ("summary_ru", models.CharField(blank=True, max_length=450)),
                ("summary_en", models.CharField(blank=True, max_length=450)),
                ("content_uz", models.TextField(max_length=12000)),
                ("content_ru", models.TextField(blank=True, max_length=12000)),
                ("content_en", models.TextField(blank=True, max_length=12000)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("alumni", "Alumni"),
                            ("event", "Event"),
                            ("achievement", "Achievement"),
                            ("general", "General"),
                        ],
                        db_index=True,
                        default="general",
                        max_length=24,
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.editorial.models.editorial_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.alumni.models.validate_avatar_size,
                        ],
                    ),
                ),
                (
                    "cover_image_url",
                    models.URLField(
                        blank=True,
                        max_length=700,
                        validators=[apps.alumni.models.validate_unsplash_image_url],
                    ),
                ),
                ("cover_image_alt", models.CharField(blank=True, max_length=220)),
                ("cover_image_credit", models.CharField(blank=True, max_length=120)),
                (
                    "cover_image_source_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[apps.alumni.models.validate_unsplash_source_url],
                    ),
                ),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("author_name", models.CharField(blank=True, max_length=160)),
            ],
            options={
                "ordering": ("-is_featured", "-published_at", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["is_published", "published_at"],
                        name="news_pub_date_idx",
                    ),
                    models.Index(
                        fields=["is_published", "category"], name="news_pub_cat_idx"
                    ),
                ],
            },
        ),
    ]
