# Generated by Django 5.2.5 on 2026-09-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editorial", "0005_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniinterview",
            name="video_duration",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="alumniinterview",
            name="video_url",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
