# Generated by Django 5.2.5 on 2026-08-28 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("alumni", "0003_alumniprofile_image_alt_alumniprofile_image_credit_and_more"),
        ("editorial", "0003_event_cover_image_alt_event_cover_image_credit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("question", "Savol"),
                            ("proposal", "Taklif"),
                            ("error_report", "Ma’lumotdagi xato"),
                            ("additional_info", "Qo‘shimcha ma’lumot"),
                            ("other", "Boshqa"),
                        ],
                        default="proposal",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("contact", models.CharField(blank=True, max_length=160)),
                ("message", models.TextField(max_length=3000)),
                ("page_type", models.CharField(blank=True, max_length=64)),
                ("page_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Yangi"),
                            ("reviewing", "Ko‘rib chiqilmoqda"),
                            ("resolved", "Hal qilindi"),
                            ("spam", "Spam"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=16,
                    ),
                ),
                (
                    "telegram_delivery_status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("sent", "Yuborildi"),
                            ("failed", "Yuborilmadi"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("telegram_message_id", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=160)),
                (
                    "alumni",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="feedbacks",
                        to="editorial.successstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Murojaat",
                "verbose_name_plural": "Murojaatlar va Takliflar",
                "ordering": ("-created_at",),
            },
        ),
    ]
