# Generated by Django 5.2.5 on 2026-09-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="feedback",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="type",
            field=models.CharField(
                choices=[
                    ("proposal", "Taklif"),
                    ("question", "Savol"),
                    ("error_report", "Xato haqida xabar"),
                    ("data_correction", "Ma’lumotni tuzatish"),
                    ("alumni_nomination", "Bitiruvchi ma’lumotini taklif qilish"),
                    ("additional_info", "Qo‘shimcha ma’lumot"),
                    ("other", "Boshqa"),
                ],
                default="proposal",
                max_length=32,
            ),
        ),
    ]
