# Generated by Django 5.2.5 on 2026-09-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("join", "Anketa / Ro‘yxatdan o‘tish"),
                            ("login", "Tizimga kirish"),
                        ],
                        default="join",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["email", "purpose", "is_verified"],
                        name="accounts_em_email_804c83_idx",
                    )
                ],
            },
        ),
    ]
