# Generated by Django 5.2.5 on 2026-08-26 02:45

import apps.alumni.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("universities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        upload_to=apps.alumni.models.avatar_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["jpg", "jpeg", "png", "webp"]
                            ),
                            apps.alumni.models.validate_avatar_size,
                        ],
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("degree", models.CharField(blank=True, max_length=80)),
                (
                    "current_company",
                    models.CharField(blank=True, db_index=True, max_length=160),
                ),
                ("position", models.CharField(blank=True, max_length=160)),
                (
                    "industry",
                    models.CharField(blank=True, db_index=True, max_length=120),
                ),
                ("city", models.CharField(blank=True, db_index=True, max_length=120)),
                (
                    "country",
                    models.CharField(blank=True, default="O‘zbekiston", max_length=120),
                ),
                ("skills", models.JSONField(blank=True, default=list)),
                ("bio", models.TextField(blank=True, max_length=1200)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("website_url", models.URLField(blank=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Ommaviy"),
                            ("alumni", "Faqat bitiruvchilar"),
                            ("university", "Faqat universitet"),
                            ("private", "Yopiq"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=16,
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("unverified", "Tasdiqlanmagan"),
                            ("pending", "Kutilmoqda"),
                            ("verified", "Tasdiqlangan"),
                            ("rejected", "Rad etilgan"),
                        ],
                        db_index=True,
                        default="unverified",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "faculty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="universities.faculty",
                    ),
                ),
                (
                    "specialty",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alumni",
                        to="universities.specialty",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeaturedAlumni",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("short_description", models.CharField(blank=True, max_length=320)),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("featured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumni",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="featured_entry",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Featured alumni",
                "ordering": ("display_order", "-featured_at"),
            },
        ),
    ]
