# Generated by Django 5.2.5 on 2026-08-26 12:42

import apps.alumni.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def populate_alumni_slugs(apps, schema_editor):
    AlumniProfile = apps.get_model("alumni", "AlumniProfile")
    used = set()
    for alumnus in AlumniProfile.objects.order_by("pk"):
        base = slugify(alumnus.full_name) or f"alumnus-{alumnus.pk}"
        candidate, suffix = base, 2
        while candidate in used or AlumniProfile.objects.exclude(pk=alumnus.pk).filter(slug=candidate).exists():
            candidate, suffix = f"{base}-{suffix}", suffix + 1
        alumnus.slug = candidate
        alumnus.save(update_fields=["slug"])
        used.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0001_initial"),
        ("universities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("description", models.TextField(blank=True, max_length=1200)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("professional", "Professional"),
                            ("academic", "Academic"),
                            ("public_service", "Public Service"),
                            ("leadership", "Leadership"),
                            ("international", "International"),
                            ("award", "Award"),
                            ("innovation", "Innovation"),
                        ],
                        default="professional",
                        max_length=32,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("order", "-year", "id"),
            },
        ),
        migrations.CreateModel(
            name="AlumniSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                (
                    "url",
                    models.URLField(
                        max_length=500,
                        validators=[apps.alumni.models.validate_https_url],
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("official_organization", "Official organization"),
                            ("government", "Government"),
                            ("news", "News"),
                            ("professional_profile", "Professional profile"),
                            ("publication", "Publication"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=32,
                    ),
                ),
                ("publisher", models.CharField(blank=True, max_length=180)),
                ("published_date", models.DateField(blank=True, null=True)),
                ("is_verified", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-is_verified", "-published_date", "id"),
            },
        ),
        migrations.CreateModel(
            name="CareerTimelineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1956),
                            django.core.validators.MaxValueValidator(2027),
                        ]
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("organization", models.CharField(blank=True, max_length=180)),
                ("description", models.TextField(blank=True, max_length=1200)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("education", "Education"),
                            ("career", "Career"),
                            ("award", "Award"),
                            ("leadership", "Leadership"),
                            ("milestone", "Milestone"),
                        ],
                        default="career",
                        max_length=24,
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ("order", "year", "id"),
            },
        ),
        migrations.AlterModelOptions(
            name="alumniprofile",
            options={"ordering": ("-is_featured", "featured_order", "full_name")},
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="biography_en",
            field=models.TextField(blank=True, max_length=2400),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="biography_uz",
            field=models.TextField(blank=True, max_length=2400),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="career_story_en",
            field=models.TextField(blank=True, max_length=6000),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="career_story_uz",
            field=models.TextField(blank=True, max_length=6000),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="featured_order",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="is_published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="published_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="seo_description",
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="seo_title",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.RunPython(populate_alumni_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="alumniprofile",
            name="slug",
            field=models.SlugField(blank=True, max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name="alumniprofile",
            name="graduation_year",
            field=models.PositiveSmallIntegerField(
                blank=True,
                db_index=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1956),
                    django.core.validators.MaxValueValidator(2027),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="alumniprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alumni_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="alumniprofile",
            index=models.Index(
                fields=["is_published", "is_featured"], name="alumni_pub_featured_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumniprofile",
            index=models.Index(
                fields=["is_published", "graduation_year"], name="alumni_pub_year_idx"
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="alumnus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="alumni.alumniprofile",
            ),
        ),
        migrations.AddField(
            model_name="alumnisource",
            name="alumnus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="alumni.alumniprofile",
            ),
        ),
        migrations.AddField(
            model_name="careertimelineitem",
            name="alumnus",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timeline",
                to="alumni.alumniprofile",
            ),
        ),
    ]
