# Generated by Django 5.2.5 on 2026-08-26 15:18

import apps.alumni.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0002_achievement_alumnisource_careertimelineitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="image_alt",
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="image_credit",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="image_source_url",
            field=models.URLField(
                blank=True,
                max_length=500,
                validators=[apps.alumni.models.validate_unsplash_source_url],
            ),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="image_url",
            field=models.URLField(
                blank=True,
                max_length=700,
                validators=[apps.alumni.models.validate_unsplash_image_url],
            ),
        ),
    ]
