# Generated by Django 5.2.5 on 2026-08-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0003_alumniprofile_image_alt_alumniprofile_image_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievement",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="careertimelineitem",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
