# Generated by Django 5.2.5 on 2026-09-04 05:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0004_alter_achievement_title_and_more"),
        ("universities", "0002_alter_faculty_options_alter_specialty_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AlumniConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_version", models.CharField(default="1.0", max_length=32)),
                ("accepted", models.BooleanField(default=True)),
                ("accepted_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
            ],
            options={
                "verbose_name": "Alumni roziligi",
                "verbose_name_plural": "Alumni roziliklari",
                "ordering": ("-accepted_at",),
            },
        ),
        migrations.AlterModelOptions(
            name="alumniprofile",
            options={
                "ordering": (
                    "-is_honorary",
                    "-is_featured",
                    "featured_order",
                    "full_name",
                )
            },
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("approved", "Tasdiqlangan"),
                    ("rejected", "Rad etilgan"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="approved_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_alumni_profiles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="current_activity",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="is_honorary",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="alumniprofile",
            index=models.Index(
                fields=["approval_status", "graduation_year"],
                name="alumni_appr_year_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alumniprofile",
            index=models.Index(
                fields=["approval_status", "is_honorary"], name="alumni_appr_hon_idx"
            ),
        ),
        migrations.AddField(
            model_name="alumniconsent",
            name="alumni",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consent",
                to="alumni.alumniprofile",
            ),
        ),
    ]
