# Generated by Django 5.2.5 on 2026-09-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0005_alumniconsent_alter_alumniprofile_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumniprofile",
            name="academic_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ilmiy darajasi yo‘q"),
                    ("phd", "Falsafa doktori (PhD)"),
                    ("dsc", "Fan doktori (DSc)"),
                ],
                default="",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="alumniprofile",
            name="academic_title",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Ilmiy unvoni yo‘q"),
                    ("docent", "Dotsent"),
                    ("professor", "Professor"),
                    ("senior_researcher", "Katta ilmiy xodim"),
                    ("academician", "Akademik"),
                ],
                default="",
                max_length=64,
            ),
        ),
    ]
