# Generated by Django 5.2.5 on 2026-09-08 06:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0007_graduationyearchangerequest_workexperience"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree_level",
                    models.CharField(
                        choices=[
                            ("bachelor", "Bakalavr"),
                            ("master", "Magistratura (Magistr)"),
                            ("phd", "Falsafa doktori (PhD)"),
                            ("dsc", "Fan doktori (DSc)"),
                            ("residency", "Ordinatura / Rezidentura"),
                            ("second_degree", "Ikkinchi oliy ta'lim"),
                            ("other", "Boshqa"),
                        ],
                        default="master",
                        max_length=32,
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        default="Qarshi davlat universiteti", max_length=220
                    ),
                ),
                ("faculty", models.CharField(blank=True, max_length=220)),
                ("specialty", models.CharField(blank=True, max_length=220)),
                (
                    "start_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1956),
                            django.core.validators.MaxValueValidator(2027),
                        ],
                    ),
                ),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1956),
                            django.core.validators.MaxValueValidator(2027),
                        ]
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="alumni.alumniprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ta'lim ma'lumoti",
                "verbose_name_plural": "Ta'lim ma'lumotlari",
                "ordering": ("order", "-graduation_year", "id"),
            },
        ),
    ]
