# Generated by Django 5.2.5 on 2026-09-20 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0008_educationexperience"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecognitionTitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                ("icon", models.CharField(blank=True, default="award", max_length=64)),
                ("description", models.TextField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Faxriy unvon",
                "verbose_name_plural": "Faxriy unvonlar",
                "ordering": ("order", "name"),
            },
        ),
        migrations.CreateModel(
            name="AlumniRecognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alumnus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recognitions",
                        to="alumni.alumniprofile",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alumni_recognitions",
                        to="alumni.recognitiontitle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bitiruvchi faxriy unvoni",
                "verbose_name_plural": "Bitiruvchilar faxriy unvonlari",
                "ordering": ("title__order", "-year", "id"),
                "unique_together": {("alumnus", "title")},
            },
        ),
    ]
