# Generated by Django 5.2.5 on 2026-09-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_recognitiontitle_alumnirecognition'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='industry',
            field=models.CharField(blank=True, max_length=160, verbose_name='Faoliyat sohasi'),
        ),
    ]
