# Generated by Django 5.2.5 on 2026-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_workexperience_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='full_name',
            field=models.CharField(max_length=160, unique=True),
        ),
    ]
