# Generated by Django 5.2.5 on 2026-09-27 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumni", "0011_unique_full_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alumnirecognition",
            options={
                "ordering": ("title__order", "-year", "id"),
                "verbose_name": "Bitiruvchi e’tirofi / mukofoti",
                "verbose_name_plural": "Bitiruvchilar e’tiroflari va mukofotlari",
            },
        ),
        migrations.AlterModelOptions(
            name="recognitiontitle",
            options={
                "ordering": ("order", "name"),
                "verbose_name": "Faxriy unvon / Mukofot",
                "verbose_name_plural": "Faxriy unvonlar va mukofotlar",
            },
        ),
        migrations.AlterUniqueTogether(
            name="alumnirecognition",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_recognitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="awarded_at",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="justification",
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[("bronze", "Bronza"), ("silver", "Kumush"), ("gold", "Oltin")],
                db_index=True,
                max_length=16,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="revocation_reason",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="revoked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="revoked_recognitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Qoralama"),
                    ("approved", "Tasdiqlangan"),
                    ("revoked", "Bekor qilingan"),
                ],
                db_index=True,
                default="approved",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alumnirecognition",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="annual_quota",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="category",
            field=models.CharField(
                choices=[
                    ("supreme_honor", "Oliy unvon"),
                    ("achievement_nomination", "Yutuqlar uchun nominatsiya"),
                    ("university_contribution", "Universitetga qo‘shgan hissa"),
                    ("traditional_status", "An’anaviy status"),
                ],
                db_index=True,
                default="achievement_nomination",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="eligibility_summary",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="has_levels",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="recognition_type",
            field=models.CharField(
                choices=[
                    ("supreme_honor", "Oliy unvon"),
                    ("nomination", "Yillik nominatsiya"),
                    ("term_status", "Muddatli maqom"),
                    ("traditional_status", "An’anaviy status"),
                ],
                db_index=True,
                default="nomination",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="symbol_name",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="term_years",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="recognitiontitle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="alumnirecognition",
            name="year",
            field=models.PositiveSmallIntegerField(
                blank=True, db_index=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recognitiontitle",
            name="description",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="recognitiontitle",
            name="name",
            field=models.CharField(max_length=160),
        ),
        migrations.AlterField(
            model_name="recognitiontitle",
            name="slug",
            field=models.SlugField(max_length=160, unique=True),
        ),
        migrations.AddIndex(
            model_name="alumnirecognition",
            index=models.Index(
                fields=["status", "is_active"], name="alumni_rec_st_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumnirecognition",
            index=models.Index(
                fields=["title", "year", "status"], name="alumni_rec_yr_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alumnirecognition",
            index=models.Index(
                fields=["alumnus", "title", "status"], name="alumni_rec_alumnus_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recognitiontitle",
            index=models.Index(
                fields=["category", "is_active"], name="rec_title_cat_act_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="recognitiontitle",
            index=models.Index(
                fields=["recognition_type", "is_active"], name="rec_title_type_act_idx"
            ),
        ),
    ]
