import { afterEach, expect, it, vi } from "vitest";
import { cleanup, render, screen, fireEvent, within } from "@testing-library/react";
import { AlumniForm } from "./alumni-form";
import { getDictionary } from "@/lib/i18n";
import { sendVerificationCode } from "@/lib/api";
vi.mock("@/lib/api", () => ({ sendVerificationCode: vi.fn(), verifyEmailCode: vi.fn(), submitAlumni: vi.fn() }));
vi.mock("@/components/auth/google-sign-in-button", () => ({ GoogleSignInButton: () => null }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
it("reports email delivery failure, does not claim delivery, and allows retry", async () => {
  const t = getDictionary("en");
  vi.mocked(sendVerificationCode).mockRejectedValueOnce(new Error("SMTP unavailable"));
  render(<AlumniForm locale="en" t={t} />);
  fireEvent.change(screen.getByPlaceholderText(t.formFullNamePlaceholder), { target: { value: "Test Graduate" } });
  fireEvent.change(screen.getByPlaceholderText(t.formEmailPlaceholder), { target: { value: "graduate@example.com" } });
  fireEvent.click(screen.getByRole("button", { name: "Kodni olish" }));
  const dialog = within(screen.getByRole("dialog"));
  fireEvent.click(dialog.getByRole("checkbox"));
  fireEvent.click(dialog.getByRole("button", { name: "Kodni olish" }));
  expect(await screen.findByRole("alert")).toHaveTextContent("SMTP unavailable");
  expect(screen.queryByLabelText("Tasdiqlash kodi")).not.toBeInTheDocument();
  vi.mocked(sendVerificationCode).mockResolvedValueOnce({ success: true, message: "Sent" });
  fireEvent.click(dialog.getByRole("button", { name: "Kodni olish" }));
  expect(await screen.findByLabelText("Tasdiqlash kodi")).toBeInTheDocument();
  expect(screen.queryByRole("alert")).not.toBeInTheDocument();
});
