import { cookies } from "next/headers";

export const locales = ["uz", "ru", "en"] as const;
export type Locale = (typeof locales)[number];

const dictionaries = {
  uz: {
    navDirectory:"Bitiruvchilar", navFeatured:"Faxrli bitiruvchilar", navJobs:"Ish imkoniyatlari", navEvents:"Tadbirlar", navMentorship:"Mentorlik", navAbout:"Platforma haqida", login:"Kirish", join:"Qo‘shilish", brand:"Bitiruvchilar Hamjamiyati", university:"Qarshi davlat universiteti",
    heroEyebrow:"QarDU bitiruvchilari hamjamiyati", heroTitle:"Bir hamjamiyat.", heroLine2:"Ko‘proq aloqa.", heroAccent:"Kengroq imkoniyatlar.", heroDescription:"QarDU bitiruvchilarini toping, professional aloqalar o‘rnating va yangi karyera imkoniyatlarini kashf eting.", findAlumni:"Bitiruvchilarni topish", joinPlatform:"Platformaga qo‘shilish", since:"1956-yildan buyon", legacy:"Ilm, tajriba va avlodlar aloqasi", searchPlaceholder:"Ism, mutaxassislik yoki kompaniya bo‘yicha qidiring", search:"Qidirish",
    universityPride:"Universitet faxri", featuredTitle:"Faxrli bitiruvchilar", featuredText:"O‘z sohasi va jamiyat rivojiga munosib hissa qo‘shayotgan QarDU bitiruvchilari.", allAlumni:"Barcha bitiruvchilar", featuredEmpty:"Faxrli bitiruvchilar ro‘yxati tayyorlanmoqda", featuredEmptyText:"Universitet jamoasi tasdiqlagan profillar tez orada shu yerda ko‘rinadi.", why:"Nega Hamjamiyat?", connections:"Aloqalar davom etadigan makon", benefit1:"Bir-biringizni toping", benefit1Text:"Fakultet, mutaxassislik, bitiruv yili yoki soha bo‘yicha hamfikrlarni qidiring.", benefit2:"Tajribani ulashing", benefit2Text:"Kasbiy yo‘lingizni ko‘rsating va yangi avlod bitiruvchilariga ilhom bering.", benefit3:"Ishonchli hamjamiyat", benefit3Text:"Ko‘rinish darajalari va universitet tasdig‘i bilan xavfsiz professional muhit.", ctaEyebrow:"Siz ham QarDU bitiruvchisimisiz?", ctaTitle:"Hamjamiyatga qo‘shiling.", ctaText:"Profilingizni yarating, kursdoshlaringizni toping va professional aloqalaringizni kengaytiring.", createProfile:"Profil yaratish",
    directoryEyebrow:"Hamjamiyat katalogi", directoryTitle:"QarDU bitiruvchilarini toping", directoryText:"Professional tajriba, yo‘nalish va joylashuv bo‘yicha hamjamiyat a’zolari bilan tanishing.", filters:"Filtrlar", year:"Bitiruv yili", industry:"Soha", company:"Kompaniya", location:"Joylashuv", results:"Natijalarni ko‘rish", found:"ta bitiruvchi topildi", previous:"Oldingi", next:"Keyingi", noResults:"Bitiruvchilar topilmadi", noResultsText:"Qidiruv yoki filtrlarni o‘zgartirib ko‘ring.", clearFilters:"Filtrlarni tozalash", loadError:"Ma’lumotlarni yuklab bo‘lmadi", retryText:"Server bilan aloqa o‘rnatilmadi. Birozdan so‘ng qayta urinib ko‘ring.", verified:"Tasdiqlangan", graduate:"QarDU bitiruvchisi",
    footerText:"Bitiruvchilarni bog‘laydigan ishonchli professional hamjamiyat.", platform:"Platforma", help:"Yordam", privacy:"Maxfiylik", welcome:"Xush kelibsiz", loginTitle:"Platformaga kirish", loginText:"QarDU bitiruvchilari hamjamiyatiga qayting.", email:"Email manzil", password:"Parol", fullName:"To‘liq ism", createAccount:"Profil yaratish", noAccount:"Hisobingiz yo‘qmi?", register:"Ro‘yxatdan o‘ting", hasAccount:"Hisobingiz bormi?", errorForm:"Ma’lumotlarni tekshiring va qayta urinib ko‘ring.", waiting:"Kutilmoqda…", joinCommunity:"Hamjamiyatga qo‘shiling", registerTitle:"Bitiruvchi profilini yarating", registerText:"Professional aloqalaringizni QarDU hamjamiyati bilan davom ettiring.", aboutGraduate:"Bitiruvchi haqida", noBio:"Bitiruvchi hali o‘zi haqida ma’lumot kiritmagan.", skills:"Ko‘nikmalar", links:"Professional havolalar", noLinks:"Havolalar kiritilmagan.", universityVerified:"Universitet tasdiqlagan", privacyTitle:"Maxfiylik siyosati", privacyIntro:"Hamjamiyat professional ma’lumotlarni faqat siz tanlagan ko‘rinish darajasiga muvofiq namoyish etadi.", publicData:"Ommaviy ma’lumotlar", privateData:"Yopiq ma’lumotlar", notFound:"Sahifa topilmadi", notFoundText:"Qidirayotgan sahifangiz mavjud emas yoki yopiq.", backDirectory:"Bitiruvchilarga qaytish",
  },
  ru: {
    navDirectory:"Выпускники", navFeatured:"Выдающиеся выпускники", navJobs:"Вакансии", navEvents:"События", navMentorship:"Наставничество", navAbout:"О платформе", login:"Войти", join:"Присоединиться", brand:"Сообщество выпускников", university:"Каршинский государственный университет",
    heroEyebrow:"Сообщество выпускников КарГУ", heroTitle:"Одно сообщество.", heroLine2:"Больше связей.", heroAccent:"Больше возможностей.", heroDescription:"Находите выпускников КарГУ, устанавливайте профессиональные связи и открывайте новые карьерные возможности.", findAlumni:"Найти выпускников", joinPlatform:"Присоединиться", since:"С 1956 года", legacy:"Знания, опыт и связь поколений", searchPlaceholder:"Поиск по имени, специальности или компании", search:"Поиск",
    universityPride:"Гордость университета", featuredTitle:"Выдающиеся выпускники", featuredText:"Выпускники КарГУ, внесшие значимый вклад в развитие своей отрасли и общества.", allAlumni:"Все выпускники", featuredEmpty:"Список выдающихся выпускников готовится", featuredEmptyText:"Подтверждённые университетом профили скоро появятся здесь.", why:"Почему Сообщество?", connections:"Место, где связи продолжаются", benefit1:"Находите друг друга", benefit1Text:"Ищите единомышленников по факультету, специальности, году выпуска или отрасли.", benefit2:"Делитесь опытом", benefit2Text:"Расскажите о своём профессиональном пути и вдохновляйте новое поколение.", benefit3:"Надёжное сообщество", benefit3Text:"Безопасная профессиональная среда с настройками видимости и подтверждением университета.", ctaEyebrow:"Вы выпускник КарГУ?", ctaTitle:"Присоединяйтесь к сообществу.", ctaText:"Создайте профиль, найдите однокурсников и расширяйте профессиональные связи.", createProfile:"Создать профиль",
    directoryEyebrow:"Каталог сообщества", directoryTitle:"Найдите выпускников КарГУ", directoryText:"Знакомьтесь с участниками сообщества по опыту, направлению и местоположению.", filters:"Фильтры", year:"Год выпуска", industry:"Отрасль", company:"Компания", location:"Местоположение", results:"Показать результаты", found:"выпускников найдено", previous:"Назад", next:"Далее", noResults:"Выпускники не найдены", noResultsText:"Измените поисковый запрос или фильтры.", clearFilters:"Сбросить фильтры", loadError:"Не удалось загрузить данные", retryText:"Нет связи с сервером. Повторите попытку позже.", verified:"Подтверждён", graduate:"Выпускник КарГУ",
    footerText:"Надёжное профессиональное сообщество, объединяющее выпускников.", platform:"Платформа", help:"Помощь", privacy:"Конфиденциальность", welcome:"Добро пожаловать", loginTitle:"Вход на платформу", loginText:"Вернитесь в сообщество выпускников КарГУ.", email:"Электронная почта", password:"Пароль", fullName:"Полное имя", createAccount:"Создать профиль", noAccount:"Нет аккаунта?", register:"Зарегистрироваться", hasAccount:"Уже есть аккаунт?", errorForm:"Проверьте данные и повторите попытку.", waiting:"Подождите…", joinCommunity:"Присоединяйтесь к сообществу", registerTitle:"Создайте профиль выпускника", registerText:"Продолжайте профессиональные связи в сообществе КарГУ.", aboutGraduate:"О выпускнике", noBio:"Выпускник пока не добавил информацию о себе.", skills:"Навыки", links:"Профессиональные ссылки", noLinks:"Ссылки не добавлены.", universityVerified:"Подтверждено университетом", privacyTitle:"Политика конфиденциальности", privacyIntro:"Сообщество показывает профессиональные данные только в соответствии с выбранным уровнем видимости.", publicData:"Публичные данные", privateData:"Закрытые данные", notFound:"Страница не найдена", notFoundText:"Страница не существует или закрыта.", backDirectory:"Вернуться к выпускникам",
  },
  en: {
    navDirectory:"Alumni", navFeatured:"Distinguished alumni", navJobs:"Jobs", navEvents:"Events", navMentorship:"Mentorship", navAbout:"About", login:"Sign in", join:"Join", brand:"Alumni Community", university:"Karshi State University",
    heroEyebrow:"KarSU alumni community", heroTitle:"One community.", heroLine2:"More connections.", heroAccent:"Broader opportunities.", heroDescription:"Find KarSU alumni, build professional connections and discover new career opportunities.", findAlumni:"Find alumni", joinPlatform:"Join the platform", since:"Since 1956", legacy:"Knowledge, experience and generations connected", searchPlaceholder:"Search by name, specialty or company", search:"Search",
    universityPride:"University pride", featuredTitle:"Distinguished alumni", featuredText:"KarSU alumni making a meaningful contribution to their profession and society.", allAlumni:"View all alumni", featuredEmpty:"The distinguished alumni list is being prepared", featuredEmptyText:"University-verified profiles will appear here soon.", why:"Why the Community?", connections:"Where connections continue", benefit1:"Find each other", benefit1Text:"Find peers by faculty, specialty, graduation year or industry.", benefit2:"Share experience", benefit2Text:"Showcase your professional journey and inspire the next generation.", benefit3:"A trusted community", benefit3Text:"A safe professional environment with visibility controls and university verification.", ctaEyebrow:"Are you a KarSU graduate?", ctaTitle:"Join the community.", ctaText:"Create your profile, find classmates and expand your professional network.", createProfile:"Create profile",
    directoryEyebrow:"Community directory", directoryTitle:"Find KarSU alumni", directoryText:"Meet community members by professional experience, field and location.", filters:"Filters", year:"Graduation year", industry:"Industry", company:"Company", location:"Location", results:"View results", found:"alumni found", previous:"Previous", next:"Next", noResults:"No alumni found", noResultsText:"Try changing your search or filters.", clearFilters:"Clear filters", loadError:"Unable to load data", retryText:"Could not connect to the server. Please try again later.", verified:"Verified", graduate:"KarSU alumnus",
    footerText:"A trusted professional community connecting alumni.", platform:"Platform", help:"Help", privacy:"Privacy", welcome:"Welcome back", loginTitle:"Sign in to the platform", loginText:"Return to the KarSU alumni community.", email:"Email address", password:"Password", fullName:"Full name", createAccount:"Create profile", noAccount:"No account yet?", register:"Register", hasAccount:"Already have an account?", errorForm:"Check your details and try again.", waiting:"Please wait…", joinCommunity:"Join the community", registerTitle:"Create your alumni profile", registerText:"Continue your professional connections within the KarSU community.", aboutGraduate:"About the graduate", noBio:"This graduate has not added a bio yet.", skills:"Skills", links:"Professional links", noLinks:"No links added.", universityVerified:"University verified", privacyTitle:"Privacy policy", privacyIntro:"The Community displays professional data only according to your selected visibility level.", publicData:"Public information", privateData:"Private information", notFound:"Page not found", notFoundText:"The page does not exist or is private.", backDirectory:"Back to alumni",
  },
} as const;

export type Dictionary = typeof dictionaries.uz;
export async function getLocale(): Promise<Locale> {
  const value = (await cookies()).get("locale")?.value;
  return locales.includes(value as Locale) ? value as Locale : "uz";
}
export function getDictionary(locale: Locale): Dictionary { return dictionaries[locale] as Dictionary; }
